Local Branch - Information UpDate

diff --git a/startksm b/startksm
--- a/startksm
+++ b/startksm
@@ -2,10 +2,23 @@
 
 # Capturar el path raíz del proyecto
 HOME_APP="$(cd "$(dirname "$0")" && pwd)"
+LOG_FILE="$HOME_APP/logs/SystemOut.log"
+
+# Capturar timestamp en segundos y milisegundos
+TIMESTAMP=$(date +%s)
+TIMESTAMP_MS=$(($(date +%s%N)/1000000))
 
 # Ejecutar el script principal
 /usr/bin/python3 "$HOME_APP/main.py"
+EXIT_CODE=$?
 
-# CheckPoint
-echo -e "\nCheckPoint - `date`\n" >> logs/SystemOut.log
+# Manejo de errores
+if [ $EXIT_CODE -ne 0 ]; then
+    echo -e "\n$TIMESTAMP :: [ERROR] :: El script main.py falló con código [$EXIT_CODE]\n" >> $LOG_FILE
+    echo -e "\n$TIMESTAMP :: [ERROR] :: El script main.py falló con código [$EXIT_CODE]\n"
+    exit $EXIT_CODE
+else
+    echo -e "\n$TIMESTAMP :: [INFO] :: El script main.py se ejecutó correctamente [$EXIT_CODE]\n" >> $LOG_FILE
+    echo -e "\n$TIMESTAMP :: [INFO] :: El script main.py se ejecutó correctamente [$EXIT_CODE]\n"
+fi
 
